name: Kuby build and push
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
      with:
        ruby-version: 2.7.5
        bundler-cache: true
        cache-version: 1
    - name: Install dependencies
      run: bundle install
    - run: RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }} bundle exec kuby -e production build
    - run: RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }} bundle exec kuby -e production push
