name: Kuby build and push
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

   # - name: Cache Docker layers
   #   uses: actions/cache@v2
   #   id: cache
   #   with:
   #     path: /tmp/.buildx-cache
   #     key: ${{ runner.os }}-buildx-ghcache-${{ github.sha }}
   #     restore-keys: |
   #       ${{ runner.os }}-buildx-ghcache-

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.5
        bundler-cache: true
        cache-version: 1

    - name: Verify dependencies
      run: bundle check

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v1

    - name: Kuby build (and push)
      #run: bundle exec kuby -e production build -- --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max --push
      run: bundle exec kuby -e production build -- --cache-from ghcr.io/kingdonb/kuby-tester:latest-assets \
        --cache-from ghcr.io/kingdonb/kuby-tester:latest --cache-from=type=gha --cache-to=type=gha,mode=max --push
      env:
        CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

  # We can omit a `kuby push` step now, because we used --push above
   # - run: bundle exec kuby -e production push
   #   env:
   #     CR_PAT: ${{ secrets.GITHUB_TOKEN }}
   #     RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

   # - # Temp fix - borrow from fluxcd/image-reflector-controller
   #   # https://github.com/docker/build-push-action/issues/252
   #   # https://github.com/moby/buildkit/issues/1896
   #   name: Move cache
   #   run: |
   #     rm -rf /tmp/.buildx-cache
   #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache
